// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace notelite.ServiceNotas {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LogicaNotasSoap", Namespace="http://tempuri.org/")]
    public partial class LogicaNotas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddNoteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateNotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteNotaOperationCompleted;
        
        /// CodeRemarks
        public LogicaNotas() {
            this.Url = "http://192.168.1.222:8090/ServiceNotas/LogicaNotas.asmx";
        }
        
        public LogicaNotas(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event AddNoteCompletedEventHandler AddNoteCompleted;
        
        /// CodeRemarks
        public event GetNotasCompletedEventHandler GetNotasCompleted;
        
        /// CodeRemarks
        public event UpdateNotaCompletedEventHandler UpdateNotaCompleted;
        
        /// CodeRemarks
        public event DeleteNotaCompletedEventHandler DeleteNotaCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddNote", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Nota[] AddNote(Nota _nuevaNota) {
            object[] results = this.Invoke("AddNote", new object[] {
                        _nuevaNota});
            return ((Nota[])(results[0]));
        }
        
        /// CodeRemarks
        public void AddNoteAsync(Nota _nuevaNota) {
            this.AddNoteAsync(_nuevaNota, null);
        }
        
        /// CodeRemarks
        public void AddNoteAsync(Nota _nuevaNota, object userState) {
            if ((this.AddNoteOperationCompleted == null)) {
                this.AddNoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNoteOperationCompleted);
            }
            this.InvokeAsync("AddNote", new object[] {
                        _nuevaNota}, this.AddNoteOperationCompleted, userState);
        }
        
        private void OnAddNoteOperationCompleted(object arg) {
            if ((this.AddNoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNoteCompleted(this, new AddNoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNotas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Nota[] GetNotas() {
            object[] results = this.Invoke("GetNotas", new object[0]);
            return ((Nota[])(results[0]));
        }
        
        /// CodeRemarks
        public void GetNotasAsync() {
            this.GetNotasAsync(null);
        }
        
        /// CodeRemarks
        public void GetNotasAsync(object userState) {
            if ((this.GetNotasOperationCompleted == null)) {
                this.GetNotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNotasOperationCompleted);
            }
            this.InvokeAsync("GetNotas", new object[0], this.GetNotasOperationCompleted, userState);
        }
        
        private void OnGetNotasOperationCompleted(object arg) {
            if ((this.GetNotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNotasCompleted(this, new GetNotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateNota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Nota[] UpdateNota(Nota _nota) {
            object[] results = this.Invoke("UpdateNota", new object[] {
                        _nota});
            return ((Nota[])(results[0]));
        }
        
        /// CodeRemarks
        public void UpdateNotaAsync(Nota _nota) {
            this.UpdateNotaAsync(_nota, null);
        }
        
        /// CodeRemarks
        public void UpdateNotaAsync(Nota _nota, object userState) {
            if ((this.UpdateNotaOperationCompleted == null)) {
                this.UpdateNotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateNotaOperationCompleted);
            }
            this.InvokeAsync("UpdateNota", new object[] {
                        _nota}, this.UpdateNotaOperationCompleted, userState);
        }
        
        private void OnUpdateNotaOperationCompleted(object arg) {
            if ((this.UpdateNotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateNotaCompleted(this, new UpdateNotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteNota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Nota[] DeleteNota(int _notaId) {
            object[] results = this.Invoke("DeleteNota", new object[] {
                        _notaId});
            return ((Nota[])(results[0]));
        }
        
        /// CodeRemarks
        public void DeleteNotaAsync(int _notaId) {
            this.DeleteNotaAsync(_notaId, null);
        }
        
        /// CodeRemarks
        public void DeleteNotaAsync(int _notaId, object userState) {
            if ((this.DeleteNotaOperationCompleted == null)) {
                this.DeleteNotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteNotaOperationCompleted);
            }
            this.InvokeAsync("DeleteNota", new object[] {
                        _notaId}, this.DeleteNotaOperationCompleted, userState);
        }
        
        private void OnDeleteNotaOperationCompleted(object arg) {
            if ((this.DeleteNotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteNotaCompleted(this, new DeleteNotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Nota {
        
        /// <remarks/>
        public int Id;
        
        /// <remarks/>
        public string Titulo;
        
        /// <remarks/>
        public string Contenido;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha;
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void AddNoteCompletedEventHandler(object sender, AddNoteCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public Nota[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Nota[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GetNotasCompletedEventHandler(object sender, GetNotasCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public Nota[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Nota[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void UpdateNotaCompletedEventHandler(object sender, UpdateNotaCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateNotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateNotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public Nota[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Nota[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void DeleteNotaCompletedEventHandler(object sender, DeleteNotaCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteNotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteNotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public Nota[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Nota[])(this.results[0]));
            }
        }
    }
}
